package handlers

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
)

// GET /postgres/{id}/export/schema
func (h *Handler) ExportSchema(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	id := chi.URLParam(r, "id")

	db, err := h.getPostgresConnection(ctx, id)
	if err != nil {
		h.writePostgresConnectionError(w, err)
		return
	}
	defer db.Close()

	ddl, err := generateSchemaDDL(ctx, db)
	if err != nil {
		h.writeError(w, http.StatusInternalServerError, "failed to generate schema export")
		return
	}

	w.Header().Set("Content-Type", "application/sql")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="schema_%s_%s.sql"`, id, time.Now().UTC().Format("20060102")))
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(ddl)) //nolint:errcheck
}

// GET /postgres/{id}/export/full
func (h *Handler) ExportFull(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 120*time.Second)
	defer cancel()

	id := chi.URLParam(r, "id")

	db, err := h.getPostgresConnection(ctx, id)
	if err != nil {
		h.writePostgresConnectionError(w, err)
		return
	}
	defer db.Close()

	ddl, err := generateSchemaDDL(ctx, db)
	if err != nil {
		h.writeError(w, http.StatusInternalServerError, "failed to generate schema export")
		return
	}

	data, err := generateDataDML(ctx, db)
	if err != nil {
		h.writeError(w, http.StatusInternalServerError, "failed to export data")
		return
	}

	w.Header().Set("Content-Type", "application/sql")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="full_%s_%s.sql"`, id, time.Now().UTC().Format("20060102")))
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(ddl + "\n\n" + data)) //nolint:errcheck
}

// generateSchemaDDL produces CREATE TABLE statements for all user tables.
func generateSchemaDDL(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_schema, table_name
		FROM information_schema.tables
		WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
		  AND table_type = 'BASE TABLE'
		ORDER BY table_schema, table_name
	`)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	type tableRef struct{ schema, name string }
	var tables []tableRef
	for rows.Next() {
		var t tableRef
		if err := rows.Scan(&t.schema, &t.name); err != nil {
			return "", err
		}
		tables = append(tables, t)
	}

	var sb strings.Builder
	sb.WriteString("-- Schema export generated by MassiCloud\n")
	sb.WriteString(fmt.Sprintf("-- Date: %s\n\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("SET client_encoding = 'UTF8';\n")
	sb.WriteString("SET standard_conforming_strings = on;\n\n")

	for _, t := range tables {
		createSQL, err := generateCreateTable(ctx, db, t.schema, t.name)
		if err != nil {
			return "", fmt.Errorf("generate table %s.%s: %w", t.schema, t.name, err)
		}
		sb.WriteString(createSQL)
		sb.WriteString("\n\n")
	}

	return sb.String(), nil
}

func generateCreateTable(ctx context.Context, db *sql.DB, schema, table string) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT
			column_name,
			data_type,
			character_maximum_length,
			numeric_precision,
			numeric_scale,
			is_nullable,
			column_default,
			udt_name
		FROM information_schema.columns
		WHERE table_schema = $1 AND table_name = $2
		ORDER BY ordinal_position
	`, schema, table)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var cols []string
	for rows.Next() {
		var name, dataType, isNullable, udtName string
		var charMaxLen, numPrecision, numScale sql.NullInt64
		var colDefault sql.NullString

		if err := rows.Scan(&name, &dataType, &charMaxLen, &numPrecision, &numScale, &isNullable, &colDefault, &udtName); err != nil {
			return "", err
		}

		colType := pgColumnType(dataType, udtName, charMaxLen, numPrecision, numScale)

		col := fmt.Sprintf("  %s %s", pgQuoteIdent(name), colType)
		if colDefault.Valid {
			col += " DEFAULT " + colDefault.String
		}
		if isNullable == "NO" {
			col += " NOT NULL"
		}
		cols = append(cols, col)
	}

	// Primary key
	pkRows, err := db.QueryContext(ctx, `
		SELECT a.attname
		FROM pg_index i
		JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
		JOIN pg_class c ON c.oid = i.indrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE i.indisprimary AND n.nspname = $1 AND c.relname = $2
		ORDER BY a.attnum
	`, schema, table)
	if err == nil {
		defer pkRows.Close()
		var pkCols []string
		for pkRows.Next() {
			var col string
			if pkRows.Scan(&col) == nil {
				pkCols = append(pkCols, pgQuoteIdent(col))
			}
		}
		if len(pkCols) > 0 {
			cols = append(cols, fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
		}
	}

	qualifiedName := pgQuoteIdent(table)
	if schema != "public" {
		qualifiedName = pgQuoteIdent(schema) + "." + pgQuoteIdent(table)
	}

	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n%s\n);", qualifiedName, strings.Join(cols, ",\n")), nil
}

func pgColumnType(dataType, udtName string, charMaxLen, numPrecision, numScale sql.NullInt64) string {
	switch dataType {
	case "character varying":
		if charMaxLen.Valid {
			return fmt.Sprintf("VARCHAR(%d)", charMaxLen.Int64)
		}
		return "VARCHAR"
	case "character":
		if charMaxLen.Valid {
			return fmt.Sprintf("CHAR(%d)", charMaxLen.Int64)
		}
		return "CHAR"
	case "numeric":
		if numPrecision.Valid && numScale.Valid && numScale.Int64 > 0 {
			return fmt.Sprintf("NUMERIC(%d,%d)", numPrecision.Int64, numScale.Int64)
		} else if numPrecision.Valid {
			return fmt.Sprintf("NUMERIC(%d)", numPrecision.Int64)
		}
		return "NUMERIC"
	case "USER-DEFINED":
		return udtName
	default:
		return strings.ToUpper(dataType)
	}
}

func generateDataDML(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_schema, table_name
		FROM information_schema.tables
		WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
		  AND table_type = 'BASE TABLE'
		ORDER BY table_schema, table_name
	`)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	type tableRef struct{ schema, name string }
	var tables []tableRef
	for rows.Next() {
		var t tableRef
		if err := rows.Scan(&t.schema, &t.name); err != nil {
			return "", err
		}
		tables = append(tables, t)
	}

	var sb strings.Builder
	sb.WriteString("-- Data export\n\n")

	for _, t := range tables {
		inserts, err := generateTableInserts(ctx, db, t.schema, t.name)
		if err != nil {
			return "", fmt.Errorf("export data %s.%s: %w", t.schema, t.name, err)
		}
		if inserts != "" {
			sb.WriteString(inserts)
			sb.WriteString("\n")
		}
	}

	return sb.String(), nil
}

func generateTableInserts(ctx context.Context, db *sql.DB, schema, table string) (string, error) {
	qualifiedName := pgQuoteIdent(table)
	if schema != "public" {
		qualifiedName = pgQuoteIdent(schema) + "." + pgQuoteIdent(table)
	}

	rows, err := db.QueryContext(ctx, fmt.Sprintf("SELECT * FROM %s", qualifiedName))
	if err != nil {
		return "", err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return "", err
	}

	quotedCols := make([]string, len(cols))
	for i, c := range cols {
		quotedCols[i] = pgQuoteIdent(c)
	}

	var valueRows []string
	for rows.Next() {
		values := make([]interface{}, len(cols))
		ptrs := make([]interface{}, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			continue
		}
		parts := make([]string, len(values))
		for i, v := range values {
			parts[i] = pgFormatValue(v)
		}
		valueRows = append(valueRows, "("+strings.Join(parts, ", ")+")")
	}

	if len(valueRows) == 0 {
		return "", nil
	}

	return fmt.Sprintf("INSERT INTO %s (%s) VALUES\n%s;\n",
		qualifiedName,
		strings.Join(quotedCols, ", "),
		strings.Join(valueRows, ",\n"),
	), nil
}

func pgQuoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func pgFormatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case []byte:
		return "'" + strings.ReplaceAll(string(val), "'", "''") + "'"
	case string:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	default:
		return fmt.Sprintf("%v", val)
	}
}
